### ISSUE TITLE
Spacesuit not working, always night not working

### ISSUE THREAD

**Issue by gummby8** [kitskub/bSpace#101]
I have the latest RB of the pluggin and bukkit. I had to add the permission to ignore suit requirements to all my users because Require suit/helmet flase did nothing and people were still dying

And alwaysnight true is not doing anything sun still rises and falls like normal

and it rains

You should add a "noblackhole" zone near spawn, 2-10 times a black hole was at spawn and chain killed people on my server

**Comment by kitskub** [comment]
Weather is no longer monitered by bSpace. For that, use a world management plugin. And what id do you use for the world?

**Comment by gummby8** [comment]
I  rolled back to the previous RB of bspace and the suffocation thing is fixed
I used some other plugins to resolve the time issue so W/E

**Comment by kitskub** [comment]
what rb did you roll back to?

**Comment by kitskub** [comment]
That should fix it

**Comment by iffa** [comment]
Is this still an issue? (closing as fix probably worked)
