### ISSUE TITLE
Non-Spout black holes

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#104]
So someone requested this a long time ago, but it was never really implemented (why?). It could be really possible:
-use an unused block (e.g. Sponge) as the black hole
-some if-statements to spice it up

**Comment by kitskub** [comment]
Hmm, I never saw this request. Should be fairly easy.

**Comment by iffa** [comment]
While experimenting with SpaceEffectPopulator, I figured that you could use the end portal block as the black hole material non-Spout

**Comment by kitskub** [comment]
The problem with thiis s that end portal blocks are unbreakable

**Comment by iffa** [comment]
We can work around that. Heard of PlayerInteractEvent? =D

**Comment by kitskub** [comment]
Is this worth creating a new event for? And as far as config, how should this work? I'm thinking instead of having "blackholes:"  be a boolean, it could either be "spout" or a block id...

**Comment by kitskub** [comment]
Or, actually, the configurable block id might be a little difficult, because it would mean we'd have to store each each every black hole's location... now, either sponge or end portal blocks would be a little easier.

**Comment by iffa** [comment]
alright

**Comment by kitskub** [comment]
So which to use?

**Comment by iffa** [comment]
end portal would look nicer

**Comment by kitskub** [comment]
Done.
