### ISSUE TITLE
Testing suffocation, found 1 problem

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#105]
Had to test this shit myself. Results in comments.

**Comment by iffa** [comment]
Suit + helmet CONFIRMED working

**Comment by iffa** [comment]
Suit only NOT WORKING

**Comment by iffa** [comment]
Helmet only CONFIRMED working

**Comment by iffa** [comment]
Result: Suit only nope.avi, rest is okay

EDIT: wait, wasnt helmet included in to suit some years ago? if yes, revert  that change and it all works as advertised?

**Comment by kitskub** [comment]
Hmm, yes, suit is bottom 3 plus helmet. But this is the way it should be. I guess we didn't change the config file...

**Comment by kitskub** [comment]
Took another look at the config. Nothing needs to be changed. I do believe that there shouldn't be just a "suit-only"(boots, leggings, and chestplate) only. If suit is on, it requires a helmet, and the helmet option doesn't matter. If not, check helmet.
