### ISSUE TITLE
Space world seed randomly changing?

### ISSUE THREAD

**Issue by gummby8** [kitskub/bSpace#108]
I use Bspace 2.1.
using bukkit R3 
multiworld 2.7.0

I can generate a brand new space map and everything will look fine, all the planets generate properly. No errors at all. After a few days my players will start to complain that their are half planets around their buildings that were not there before. When I got to check, sure enough a good 30-40% of the already generated planets are sliced up or have other planets generating into them. If I highlight the planets I know existed days ago with world edit and use //regen (rolls back the region to its original state using the world generator and seed), the planet disappears as if it was never there in the first place! Sometimes it will generate an entirely new planet!

The plugin is acting like the seed number is changing all the time, even though when I look in my multiworld config, the seed is exactly the same, what is worse is it is cutting up already generated planets with whatever new seed it thinks it has.

**Comment by iffa** [comment]
could be the planet generator comes up with its own seed

**Comment by kitskub** [comment]
I know what's happening. The planet generator does not shift the random generator as it pertains to a chunk. I will take another look at it and see what I can do.

**Comment by kitskub** [comment]
Fixed in the latest dev build.
