### ISSUE TITLE
schematic loading

### ISSUE THREAD

**Issue by SamusChief** [kitskub/bSpace#109]
When I try to create a world that loads schematics of space-stype stuff using my up-to-date dev build of multiverse using bSpace2.3, it crashes and does not create the world.

**Comment by kitskub** [comment]
Thank you for the bug report. Can you post your console log?

**Comment by Gnarler** [comment]
I second this, when I try to make a space world it gives me an internal error, however if I type it again, it works for some reason.  However, the world will soon be deleted.

**Comment by Gnarler** [comment]
heres the issue with the schematics.
http://pastebin.com/pqQvqMC3
My schematics are mce not gzip. 
Also the spawn chunk enderportal blocks keep generating and soon make a pillar of endstone.
Thanks.

**Comment by Gnarler** [comment]
I tried saving the schematics into mcedit and then exporting them but they dont work like that either.

Is there any way we can get our schematics into bSpace?

**Comment by Gnarler** [comment]
I tried your #77 release from Jenkins.  The console said it couldn't load the schematic.

2012-05-03 05:12:51 [INFO] [bSpace] Enabling bSpace vv2.3
2012-05-03 05:12:51 [WARNING] [bSpace] There was a problem while loading schematic file 'goldroid2.schematic'! Are you sure it's a schematic: Not in GZIP format
2012-05-03 05:12:51 [INFO] [bSpace] The plugin will now start sending usage stats. You can disable this plugins/PluginMetrics/config.yml!
2012-05-03 05:12:52 [INFO] [bSpace] Enabled version v2.3.

**Comment by kreltaz** [comment]
Hi,

I'm new to this addon and really like it, so thanks for creating it.
I was a bit sad when I tried to load my asteroid schematics and found that bSpace doesn't like them. So I looked up the schematic loading process into the code and it seems there is a problem with this part:

me.iffa.bspace.api.schematic.SpaceSchematicHandler.java at line 169, it reads:

```
nbt = new NBTInputStream(new GZIPInputStream(fis));
```

Here is the constructor of NBTInputStream :

```
public NBTInputStream(InputStream is) throws IOException {
    this.is = new DataInputStream(new GZIPInputStream(is));
}
```

It actually does a double GZIPInputStream 'encapsulation'.
I modified the function so the try block looks like this:

```
public static void loadSchematic(File file) {
    try{
        FileInputStream fis = new FileInputStream(file);
        NBTInputStream nbt = new NBTInputStream(fis);
        Schematic schematic = loadSchematic(file.getName().replaceAll(".schematic", ""), nbt);
        if (nbt != null) {
            nbt.close();
        }
        if (fis != null) {
            fis.close();
        }
        schematics.add(schematic);
        MessageHandler.debugPrint(Level.INFO, "Added Schematic '" + file.getName() + "' to schematics list:\n" + schematic.getWidth() + "\n" + schematic.getHeight() + "\n" + schematic.getLength() + "\n" + schematic.getBlocks() + "\n" + schematic.getBlockData());
    } catch (Exception e) {
        MessageHandler.print(Level.WARNING, "There was a problem while loading schematic file '" + file.getName() + "'! Are you sure it's a schematic: " + e.getMessage());
    }
}
```

Rebuilt and my asteroids started poping out of space.
I'm sure there is a proper way to fix it, since it gets rid of the isGZIP check, but since all my schematics are gzip'ed, it doesn't really matter to me.
Hope this helped.

**Comment by kitskub** [comment]
@kreltaz Thank you soo much! I will add that code in and push it!

**Comment by kitskub** [comment]
If someone can confirm this works: http://ci.chrisgward.com/job/bspace/85/

**Comment by kreltaz** [comment]
Using the new build, schematics seem to load fine.

**Comment by kitskub** [comment]
Yes! Thanks again @kreltaz

**Comment by kreltaz** [comment]
You're welcome! It's a great addon by the way, I'm glad if I contributed.
