### ISSUE TITLE
The World is not a Space World

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#11]
This is the message I get when I try to use /space enter. I'm pretty sure that this is because createSpaceWorlds() is not getting called, because MV-core is available. If I'm correct, that's where all the space worlds are created/loaded. So, anything that relys on that to check if its a space world won't work correctly.

**Comment by iffa** [comment]
Yeah, if you have multiverse Bananaspace "is supposed" to leave spaceworld creation to MV

**Comment by kitskub** [comment]
Well, I think what you did should fix it. If you want MV to take over on world creation, it shouldn't take too much recoding.
