### ISSUE TITLE
Chances unclear

### ISSUE THREAD

**Issue by Gnarler** [kitskub/bSpace#112]
I can't figure out your method for coding the chances and density. Is a high number for blackhole chance going to give alot of a few?  

Also the density, would a higher number be "more dense" then a lower number?

Please put a comment in your post to clarify this, as well as reccommending people use multiworld instead of multiverse, as multiverse does not like bSpace.

Thank you.

**Comment by kitskub** [comment]
Info has been added:
Higher number for blackhole chance gives more.
Higher density means higher potential planets

And, nowhere do we recommend multiverse. We use it as an example, though.
