### ISSUE TITLE
Suffocation problem again! C: Hooray! 

### ISSUE THREAD

**Issue by Frinckles** [kitskub/bSpace#113]
Great plugin by the way, just running into a small problem.

  I generated my world, it came out perfectly but just like so many other people, players are not suffocating. I thought at first that it might be because I was on the 'OP' list, or maybe it was because I was in creative. I turned both off and I'm still not suffocating. I've tried every possible option; Suit to true, helmet to false and vice versa.. nothing. I am in fact not wearing any armor and my computer is plugged in. 

  Anyway, here's the error log!

[=========================================================================]

```
    06:16:17 [WARNING] Task of 'bSpace' generated an exception
```

java.lang.NullPointerException
        at me.iffa.bspace.api.SpacePlayerHandler.hasSuit(SpacePlayerHandler.java
:86)
        at me.iffa.bspace.api.SpacePlayerHandler.checkNeedsSuffocation(SpacePlay
erHandler.java:157)
        at me.iffa.bspace.runnables.SuffacationRunnable.run(SuffacationRunnable.
java:40)
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(C
raftScheduler.java:126)
        at net.minecraft.server.MinecraftServer.w(MinecraftServer.java:524)
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:450)
        at net.minecraft.server.ThreadServerApplication.run(SourceFile:492)

[=================================================================================]

I'm rockin' the following: 

```
              craftbukkit-1.2.5-R2.0
              bSpace-v2.3
              Multiverse-Core-2.4
```

 The error itself just kind of pops up whenever I step foot in my space world using the command '/mv tp space'. If you guys need any more information on the error feel free to ask, hope this helped. I couldn't find another ticket of this error anywhere else even though quite a few people are having the problem so I decided to make one.

```
     Good luck and thanks again for the great generator. 
```

 P.S. On a side note, is there anyway to add some variation to the asteroid shapes? Like make them more rounded, larger etc. Also, is it possible to increase the density of the random bits of stone you see floating? I want moar. 

```
                  -Frinckles
```

**Comment by Frinckles** [comment]
Oh gosh, that's what I get for not knowing the Github markdown. My post looks 40 kinds of stupid.

**Comment by iffa** [comment]
too old
