### ISSUE TITLE
Permissions Request

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#12]
I see that in some of the latest builds, Permission support has been replaced with superperms. I think that instead of replacing Permissions, it should only add support. I say this because I know many Admins have not yet which, and many have reasons for not switching.

**Comment by iffa** [comment]
Permissions is dead. Nijikokun doesn't support it, so why should we? Everyone should have migrated to PEX already.

**Comment by kitskub** [comment]
Sounds good.
