### ISSUE TITLE
Pinapp2-style portal to go to space

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#19]
Just so no external plugins, commands or anything need to be used (when going to non-mv spaceworlds)

**Comment by kitskub** [comment]
So, you want all portals that are created in a space world to go to a non-space world?

**Comment by iffa** [comment]
Nonon, I'll explain later

**Comment by iffa** [comment]
Okay, a custom portal to go to a space world (don't know how that would happen), like glowstone instead of obsidian. And, it would help if you hopped onto #bananacode on EsperNet when youre online, but you seem to be active when im zzZZ so.

**Comment by kitskub** [comment]
Ok, this should be simple. What block? Should it be configurable, or preset?

**Comment by iffa** [comment]
Go for glowstone for now, but make it configurable (global)

**Comment by iffa** [comment]
Don't forget 1.3 releaSE sunday

**Comment by kitskub** [comment]
So, unfortunately, I wasn't able to work on this this weekend. But I am currently working on it.

**Comment by kitskub** [comment]
It is a lot of work, and its making me question whether adding another portal-type system is necessary. I think between /space enter and all the portal plugins out there, this shouldn't be needed.

**Comment by iffa** [comment]
Maybew

**Comment by kitskub** [comment]
So, is this a nix?
