### ISSUE TITLE
Have BananaSpace NOT generate a default world.

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#32]
A few reasons why this should be done:
1)It doesn't allow the user to edit the settings to their liking
2)It will only be known to BananaSpace. Any world manager plugins won't know about it nor will it be in the bukkit.yml. And, this is unconfirmed, but some new chunks may not generate.

**Comment by iffa** [comment]
I guess that could work.

**Comment by kitskub** [comment]
Done.
