### ISSUE TITLE
Satellite populator

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#36]
As suggested by @ledhead900.

**Comment by kitskub** [comment]
I think we should move this to 1.5,rather than 1.4.

**Comment by iffa** [comment]
Yes, it will probably not be done for 1.4 so it can then just be moved to the 1.5 milestone.

**Comment by iffa** [comment]
I will only add a satellite populator for now.

**Comment by iffa** [comment]
Alright, it's done.
