### ISSUE TITLE
Custom space-ish blocks using Spoutcraft API?

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#41]
I heard it's possible now.

**Comment by kitskub** [comment]
I think I've got it. Any specific texture pack you're thinking about?

**Comment by iffa** [comment]
Not really.

**Comment by kitskub** [comment]
Well, can you give me a link to the texture pack that you want to use at least temporarily. I think I'm going to make one specifically for the plugin...

**Comment by iffa** [comment]
No idea here

**Comment by iffa** [comment]
Moving to v2.

**Comment by kitskub** [comment]
This is already in...

**Comment by iffa** [comment]
Derp! didnt notice
