### ISSUE TITLE
No Helmet/Suit Damage Sustained After Death.

### ISSUE THREAD

**Issue by hi00ih** [kitskub/bSpace#49]
When a helmet or armor piece is removed from the player, when they take damage enough to die, when the respawn they are still constantly taking the same amount of damage untill logging out and back in.

**Comment by iffa** [comment]
More info?

**Comment by hi00ih** [comment]
Its there sorry i hit enter too fast sometimes.

**Comment by iffa** [comment]
Alright, now i got it

**Comment by hi00ih** [comment]
Yeah, kinda serious bug. Die once and you die until you relog and if you were to take off the chestplate you wouldn't even have the chance to ask for help!

**Comment by iffa** [comment]
Moving to v2.

**Comment by hi00ih** [comment]
Alright, although it makes the plugin hard to use without godmode :0

**Comment by iffa** [comment]
Yeah yeah

**Comment by iffa** [comment]
This was simple, the event for entity death wasn't registered, but the fix was there. :D

**Comment by hi00ih** [comment]
Thanks, waiting on release when your ready.

**Comment by iffa** [comment]
I'll push this change to the 1.4_2 branch, I'll link you to a "fixed" build in a sec.

**Comment by iffa** [comment]
https://github.com/iffa/BananaSpace/raw/bs1/target/BananaSpace-1.4_2.jar
Fixed missing registerEvent

**Comment by hi00ih** [comment]
Thanks a lot! I can use this now. Now when the multiverse problems are fixed i can use this to its full potential and my users will be happy.

**Comment by iffa** [comment]
:) You'll have to wait for the new world gen system thing, but I'll let you know once that's done.

**Comment by hi00ih** [comment]
Alright sounds good. Oh and one thing if you have heard of the voxel box's new adventure map, you may want to make a mode that generates space like that. I know a lot of people on my server were asking if space looked like that.

**Comment by iffa** [comment]
I'm not a Voxel fanboy, can I have screenshots?

**Comment by hi00ih** [comment]
Uhh i'll look and see if i can download the map. Neither am I lol.
