### ISSUE TITLE
v1.4_2 config to v2(-dev) config

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#57]
Just to make updating to v2 as easy as possible. The nodes in worlds should be copied over to ids.yml. Also new nodes should be added to the configs (if any). 

NOTE: All this **automatically!** right when starting up v2 with a v1.4 config!

**Comment by kitskub** [comment]
The converter is not currently working.

**Comment by iffa** [comment]
ids:
  world_space:
    generation: {}
    suit: {}
    helmet: {}
    breathingarea: {}

I noticed.

**Comment by iffa** [comment]
Done
