### ISSUE TITLE
move stats config to bananaspace folder

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#59]
I've thought about it and why should stats get its own folder. It doesn't pertain to any plugin but bananaspace.

**Comment by iffa** [comment]
Iirc swearwords license dosentti allow modifying

**Comment by kitskub** [comment]
Dang it

**Comment by kitskub** [comment]
@iffa, now that we changed to a different class, the new one allows modifying. In my opinion, I think we should change it.

**Comment by kitskub** [comment]
Done
