### ISSUE TITLE
Documentation for the new "wgen system" (ids, that is)

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#61]
I have no idea how to use it. Maybe you add a page for the devbukkit thing about it. OFC tell its for v2(-dev)

**Comment by kitskub** [comment]
I updated all the bukkit dev pages, and put them in a new sub-folder. I will probably create a full page of explanation later.

**Comment by kitskub** [comment]
Is this done?

**Comment by iffa** [comment]
yes
