### ISSUE TITLE
Spawn block like there used to be

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#65]
You know it's not fun to just fall down forever to your death :P

**Comment by kitskub** [comment]
what do you mean? Is there not a starting planet?

**Comment by iffa** [comment]
Well, no

**Comment by iffa** [comment]
Well, no

**Comment by kitskub** [comment]
Hmm, that's odd. It's still in the code...

**Comment by kitskub** [comment]
Ok, finally got time to look at this. Yes, it is still in the code. I'm thinking, maybe you're not spawning at 0,0?

**Comment by kitskub** [comment]
Ok, yes, there is still a spawn block. I don't know if there is a way to force where the initial spawn point is though...
