### ISSUE TITLE
Suffocation ignores suit & helmet settings

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#82]

**Comment by kitskub** [comment]
Still? I thought I fixed this...

**Comment by kitskub** [comment]
Possible fix in https://github.com/iffa/bSpace/commit/9bfc9bce2d4f3e73705ea76d50ca8f454ebbd71b

**Comment by iffa** [comment]
I'll say possible fix is enough

**Comment by iffa** [comment]
yes it still does

**Comment by kitskub** [comment]
How so?

**Comment by kitskub** [comment]
Got it. And this error dates back all the way. Bukkit.getScheduler().isCurrentlyRunning() != Bukkit.getScheduler().isQueued()!!!!! Fixing now

**Comment by iffa** [comment]
:DD:

**Comment by ghost** [comment]
I have a similar problem on v2. I am using stargates to enter space, and then start out in a breathable area. However, even tho people got the full suit on, which is chainmail, they will still suffocate when going outside. Other people can walk around outside without any suit on at all, and not suffocate. And they dont have the unsuffocate permission, i checked:/

**Comment by iffa** [comment]
If we get confirmation of this, will reopen

**Comment by kitskub** [comment]
Confirmed.

**Comment by kitskub** [comment]
On second thought, this is a duplicate issue. Closing. See #89 for updates
