### ISSUE TITLE
When a black hole sucks in the player...

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#83]
the player should look at it.

**Comment by iffa** [comment]
that can be done by somehow changing yaw & pitch, but how to calculate such to look at the block, no idea

**Comment by kitskub** [comment]
I've got a rough idea started. And it works for some. But some it does not.

**Comment by kitskub** [comment]
May instead look around randomly, instead of at block.

**Comment by kitskub** [comment]
Done
