### ISSUE TITLE
Spout Gravity persists

### ISSUE THREAD

**Issue by ghost** [kitskub/bSpace#88]
Hi. On my world i use Inception to layer the worlds. I noticed that if inception teleports me from bSpace to the world below, the low gravity will stay. It stays until i die or relog.

**Comment by iffa** [comment]
Could be

**Comment by kitskub** [comment]
What version of inception are you using?

**Comment by ghost** [comment]
it says Version 1.04dev0.5 in console

**Comment by kitskub** [comment]
You do know that the last time that was updated was for CB version 1060, right? I have no clue if that is the cause of the problem or not.I have to assume not. What CB and SpoutPlugin versions are you using?

**Comment by kitskub** [comment]
Fixed in latest build.
