### ISSUE TITLE
bukkit load of problems

### ISSUE THREAD

**Issue by mmuziek** [kitskub/bSpace#89]
1. when i die. i keep dieing even when i spawn in normal world. wich has no bspace.
2. i created a sealed planed. now if i take of my helmed i suffocate.

can anyone help me. point 2 is most wanted.
i made a space station but if i put off my helmed i die.
thanks in advance

i use Bspace 2 (latest)
i use bukkit recommended build for 1.0.1

in addition it doesnt stay night. it goes normal cycle.

evey reload/restart changes the problems. if i reload. then i dont suffocate anymore but as soon as i leave space and rejoin space i die. even when i am in a station.

**Comment by kitskub** [comment]
Thanks for the report. I will check this as soon as possible

**Comment by ghost** [comment]
Never reload your server, things go wrong. Either reload the plugin, if it has a reload command, or restart the server.

The only places that are breathable are those that meet the breathable requirements. You can configure it on the config, atm. it checks if you have a block x distance above you. Default is 5. So if you make a room thats higher than 5 for example, you will start to suffocate

**Comment by kitskub** [comment]
Try this one

**Comment by iffa** [comment]
It should stay night no matter what happens.

**Comment by mmuziek** [comment]
em i dont know how to use those codes u send me.
i am not a java programmer. 

i get many link now thats fine but they point me to java files wich i dont understand..

**Comment by kitskub** [comment]
http://ci.chrisgward.com/job/bSpace/ find the latest build and use it

**Comment by kitskub** [comment]
Unless someone says otherwise, I guess this is fixed.

**Comment by mmuziek** [comment]
it still happens. many times. but its handable.

**Comment by kitskub** [comment]
Are you doing to the same process as before?

**Comment by mmuziek** [comment]
i have set max hight to 8.
and when someones entering the space station sometimes they suffocate.
and they stay suffocating whereever they are on normal world and all other stations until i do a server restart

**Comment by anon5000** [comment]
I am also having this exact same problem.

**Comment by kitskub** [comment]
Can you start a new issue and describe your process EXACTLY. And could you use pastie and let me see your config.yml and ids.yml. I, myself, have no problems with this, so if there is an issue, I need to know how to recreate it.
