### ISSUE TITLE
Can't get bSpace to generate a space world.

### ISSUE THREAD

**Issue by walkerpwns** [kitskub/bSpace#91]
Hello, I have installed this plugin and can not seem to get it to work with multiverse. It probably is some completely noobish error im doing but here is what i have been doing. I have been using the command "/mv create Space normal -g BananaSpace:1" and every time it creates the world it has a normal world seed without space at all and when i do "/space enter Space" it says it is not a space world, which obviously it is not. If anybody could help me that would be greatly apprieciated. I am using bSpace v2 by the way with the proper bukkit build and the 1337 version of multiverse. I also have tried to make this world generate in the bukkit.yml file with a format like this: 

worlds: 
  space: 
    generator: BananaSpace

When doing that, it does not even attempt to generate a world on the server reboot. All the in game commands work just fine but the generation in general just does not work. Pl0x help this noob XD

P.S.: I am using the 1.0.1 version of bukkit which is reccomended build and get absolutely no errors or anything, it just does not load the space world.

**Comment by iffa** [comment]
it's bSpace, not BananaSpace

**Comment by walkerpwns** [comment]
Oh, thanks. It has generated the world. Now, I have been messing around in the config files and have specifically turned off black hole generation and rebooted the server and loaded space again, but the black holes still seem to generate when i turned the black hole option in the id to false.

**Comment by kitskub** [comment]
Hmm...can you describe the exact process that you take?

**Comment by kitskub** [comment]
Issue?

**Comment by walkerpwns** [comment]
I have given up with this plugin for now. It has to many bugs, it generates black holes even when it is turned off in the config and id file.

**Comment by kitskub** [comment]
I will test for confirmation of this. Although, it would help to know the exact process that you went through to make them generate when off. I am sorry that you find the plugin to have too many bugs. I will sort them out, and notify you when they are.

**Comment by walkerpwns** [comment]
I am not currently in a position to replicate the scenario. when i get home i will try it again.

**Comment by kitskub** [comment]
I have confirmed this and am now fixing it.

**Comment by kitskub** [comment]
Actually, I am sorry. I cannot confirm this. I had troubles with my configuration file. I fixed that and the problem is gone. Perhaps you are having the same issue. If you want to put your ids.yml into pastie.org, and post the link, I may be able to help you.

**Comment by walkerpwns** [comment]
I was able to get the plugin working. It just was me not properly linking the ids.yml to the world name in bukkit.ymlI do have another request though and was woundering if you would be able to help me with this for my server. We are currently working on a space prison map and I know your space plugin has a gravity feature. Well I was woundering if you could help us make a separate plugin so that if a person jumps they would do something like float up a few blocks. Like think of this. A prison full of people where in the halls pvp is actually a tactical challenge because people will be flying and walking on the ceiling and floors. It would really add a whole new demension to our server. We would be willing to pay you for development of this plugin as well if you wouldnt mind making something like that separate from the space plugin.<3<3<3<3 TestcraftGaming.inc

**Comment by kitskub** [comment]
How can I contact you besides on this issue?

**Comment by walkerpwns** [comment]
> I'll pm you.
> On github or bukkit.org? If it's more convienient we could even talk in game. Testcraft.g.nfoservers.com

**Comment by kitskub** [comment]
I can't pm you on github. If your bukkit is the same as your github, I'll pm you on there. I might get on later.

**Comment by walkerpwns** [comment]
My bukkit name is walkerpwns as well. Thank you so much by the way to taking interest in my request. You have no idea how thankfull I am :D
