### ISSUE TITLE
Start using the new event system

### ISSUE THREAD

**Issue by iffa** [kitskub/bSpace#95]
All event related, DEPRECATED BAHHHHH

https://github.com/Bukkit/Bukkit/commit/e35037ab50157b006d00cba6d1b2c898e2bf5258#diff-126

**Comment by kitskub** [comment]
I actually like the new system. Much cleaner

**Comment by iffa** [comment]
http://forums.bukkit.org/threads/new-event-system.55249/

Leaving it to you, I'm busy-ish
(I can do something though)

**Comment by iffa** [comment]
If it works, it's done.

**Comment by kitskub** [comment]
Looks good.
