### ISSUE TITLE
SpaceTexture not available for download.

### ISSUE THREAD

**Issue by kitskub** [kitskub/bSpace#99]
Well, I went to download spacetexture.zip. Got an error. So, that should be fixed. And possibly look in to someone making one for us. Or one of us finishing it.

**Comment by LeoVerto** [comment]
Yes, that would be really cool. Also adding a modified pumpkin overlay (as it it the default space helmet) would be great.

**Comment by kitskub** [comment]
If this is still wanted, we should open it as a BukkitDev ticket as that system is more intuitive. So, closing this.
